services:
  frontend:
    build:
      context: .
    container_name: swallet-client
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules:/app/node_modules
    working_dir: /app
    command: yarn dev