services:
  frontend:
    build:
      context: .
    container_name: swallet-client
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Use an anonymous volume for node_modules
    command: sh -c "yarn install && yarn dev"
    working_dir: /app
