services:
  db:
    image: postgres:15-alpine
    volumes:
      - swalletdb_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    env_file:
      - ./server/.env  # Correct path from root
    networks:
      - app-network

  backend:
    extends:
      file: ./server/docker-compose.server.yml
      service: swallet
    env_file:
      - ./server/.env # Correct path from root
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
  frontend:
    extends:
      file: ./client/docker-compose.client.yml
      service: frontend
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:8000

networks:
  app-network:
    driver: bridge

volumes:
  swalletdb_data:
  media_volume: # Define volumes used by services here
