# Generated by Django 5.2 on 2025-04-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_last_login_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
