# Generated by Django 5.2 on 2025-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_last_login'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passkeychallenge',
            index=models.Index(fields=['is_used'], name='core_passke_is_used_397a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
    ]
