services:
  db:
    image: postgres:15-alpine
    volumes:
      - swalletdb_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    env_file:
      - .env  # Reference the .env file

  swallet:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: ${DEBUG}
    env_file:
      - .env  # Reference the .env file
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  swalletdb_data:
  media_volume:
