# Generated by Django 5.2 on 2025-04-19 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassKeyCredential',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('algorithm_type', models.CharField(choices=[('ECDSA', 'ECDSA'), ('RSA', 'RSA'), ('P256', 'P256')], max_length=10)),
                ('attestation_object', models.TextField(null=True)),
                ('signature_counter', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
